server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: model-master
  profiles:
    active: ${ACTIVE:dev}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/uou}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${DB_USER:root}
    password: ${DB_PWD:1113}
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss