server:
  port: ${SERVER_PORT:8080}
  application:
    name: uou
  profiles:
    active: ${ACTIVE:dev}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://43.139.111.22:3306/uou}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${DB_USER:root}
    password: ${DB_PWD:gl-mysql}
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss